#!/usr/bin/env python3
import csv
import re

# New companies gathered from goplaces searches
new_companies = [
    # GUADALAJARA (Jalisco)
    ("C&A", "Mexico", "Guadalajara", "1+", "Retail"),
    ("ELLAS boutique GDL", "Mexico", "Guadalajara", "1+", "Retail Apparel and Fashion"),
    ("El 5to Poder", "Mexico", "Guadalajara", "1+", "Retail"),
    ("VERTICHE Guadalajara", "Mexico", "Guadalajara", "1+", "Retail Apparel and Fashion"),
    ("Barceló Ropa de importación por mayoreo", "Mexico", "Guadalajara", "1+", "Retail"),
    ("Witch mx", "Mexico", "Guadalajara", "1+", "Retail Apparel and Fashion"),
    ("Todomoda", "Mexico", "Guadalajara", "1+", "Retail Apparel and Fashion"),
    ("Tienda De Ropa Para Dama Y Caballero A La Moda", "Mexico", "Guadalajara", "1+", "Retail"),
    # MONTERREY (Nuevo León)
    ("Fashion Drive", "Mexico", "Monterrey", "1+", "Retail"),
    ("MAS MAS Boutique", "Mexico", "Monterrey", "1+", "Retail"),
    ("Ruth Mar", "Mexico", "Monterrey", "1+", "Retail"),
    ("Martha Boutique", "Mexico", "Monterrey", "1+", "Retail"),
    ("First Communion Dresses Monet Boutique", "Mexico", "Monterrey", "1+", "Retail"),
    ("Mockingbird Monterrey", "Mexico", "Monterrey", "1+", "Retail"),
    ("EGOmode", "Mexico", "Monterrey", "1+", "Retail"),
    ("Choocolatte", "Mexico", "Monterrey", "1+", "Retail"),
    ("Gala Boutique", "Mexico", "Monterrey", "1+", "Retail"),
    ("The Closet", "Mexico", "Monterrey", "1+", "Retail"),
    # MEDELLÍN (Antioquia)
    ("La Bodega", "Colombia", "Medellín", "1+", "Retail"),
    ("Solo Amor Moda", "Colombia", "Medellín", "1+", "Retail Apparel and Fashion"),
    ("World Fashion Center", "Colombia", "Medellín", "1+", "Retail"),
    ("th Moda Femenina", "Colombia", "Medellín", "1+", "Retail Apparel and Fashion"),
    ("Adrissa Punto de Fabrica", "Colombia", "Medellín", "1+", "Retail"),
    ("Imperio de la Moda", "Colombia", "Medellín", "1+", "Retail"),
    ("Ropa al por mayor Medellín la bodega", "Colombia", "Medellín", "1+", "Retail"),
    ("Candelaria Moda", "Colombia", "Medellín", "1+", "Retail"),
    ("CHD moda", "Colombia", "Medellín", "1+", "Retail"),
    # PUEBLA
    ("Boutique Paris Puebla", "Mexico", "Puebla", "1+", "Retail"),
    ("Exclusive Love Boutique", "Mexico", "Puebla", "1+", "Retail"),
    ("Cero", "Mexico", "Puebla", "1+", "Retail"),
    ("Norma", "Mexico", "Puebla", "1+", "Retail"),
    ("Mi Sueño Boutique Puebla", "Mexico", "Puebla", "1+", "Retail"),
    ("Boutique Latina", "Mexico", "Puebla", "1+", "Retail"),
    ("Vintage Store Puebla", "Mexico", "Puebla", "1+", "Retail"),
    ("Mexicanisima boutique", "Mexico", "Puebla", "1+", "Retail"),
    ("Fast Fashion Puebla", "Mexico", "Puebla", "1+", "Retail"),
    ("Filth Shop", "Mexico", "Puebla", "1+", "Retail"),
    # LEÓN (Guanajuato)
    ("Factory Shops Outlet León", "Mexico", "León", "1+", "Retail"),
    ("Plaza Mayor León", "Mexico", "León", "1+", "Retail"),
    ("hellofashion", "Mexico", "León", "1+", "Retail Apparel and Fashion"),
    ("Del Sol León", "Mexico", "León", "1+", "Retail"),
    ("Mercado Comonfort Ropa", "Mexico", "León", "1+", "Retail"),
    ("Yuny Moda León", "Mexico", "León", "1+", "Retail"),
    ("Pink and Yellow", "Mexico", "León", "1+", "Retail"),
    ("La Güera Jeans & Moda", "Mexico", "León", "1+", "Retail"),
    ("Plaza del Zapato", "Mexico", "León", "1+", "Retail"),
    ("Almacenes Roma de León", "Mexico", "León", "1+", "Retail"),
    # CALI (Valle del Cauca)
    ("SHOP MODA", "Colombia", "Cali", "1+", "Retail"),
    ("KD Tienda De Moda", "Colombia", "Cali", "1+", "Retail"),
    ("Temple of Fashion", "Colombia", "Cali", "1+", "Retail"),
    ("BL Fashion centro comercial el tesoro", "Colombia", "Cali", "1+", "Retail"),
    ("Moda Centro Cali", "Colombia", "Cali", "1+", "Retail"),
    ("Laboutiquecali", "Colombia", "Cali", "1+", "Retail"),
    ("El Templo de la Moda - Alameda", "Colombia", "Cali", "1+", "Retail"),
    ("FASHION CENTER MALL", "Colombia", "Cali", "1+", "Retail"),
    ("Templo de la moda", "Colombia", "Cali", "1+", "Retail"),
    ("Ropa para Mujer Trapos y Moda", "Colombia", "Cali", "1+", "Retail"),
    # TIJUANA (Baja California)
    ("Lua Boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("Love Forever Boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("High Street Plaza Rio", "Mexico", "Tijuana", "1+", "Retail"),
    ("Adelin's Boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("Azul boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("AW boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("K27 Boutique", "Mexico", "Tijuana", "1+", "Retail"),
    ("Yesi Trendy Tijuana", "Mexico", "Tijuana", "1+", "Retail"),
    ("LILIANA REAL SUCURSAL PASEO DEL RÍO", "Mexico", "Tijuana", "1+", "Retail"),
    ("Top Girl", "Mexico", "Tijuana", "1+", "Retail"),
    # QUERÉTARO
    ("Lotes Linda (Ropa de dama mayoreo)", "Mexico", "Querétaro", "1+", "Retail"),
    ("Bershka Querétaro", "Mexico", "Querétaro", "1+", "Retail"),
    ("NEW MODA", "Mexico", "Querétaro", "1+", "Retail"),
    ("Marcony Boutique", "Mexico", "Querétaro", "1+", "Retail"),
    ("Omadi Boutique", "Mexico", "Querétaro", "1+", "Retail"),
    ("Todomoda Querétaro", "Mexico", "Querétaro", "1+", "Retail"),
    ("Tienda de Vestidos Frida Boutique", "Mexico", "Querétaro", "1+", "Retail"),
    ("Vestidos Ankara Querétaro", "Mexico", "Querétaro", "1+", "Retail"),
    ("Maison Janeth Renta y Venta de Vestidos", "Mexico", "Querétaro", "1+", "Retail"),
    ("Shasa Querétaro", "Mexico", "Querétaro", "1+", "Retail"),
    # BUCARAMANGA (Santander)
    ("Bonitas Boutique Moda", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("MIA Alma Mia", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("WO! Boutique", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("La Guapa", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("Moana boutique de sol", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("Maemi Oficial", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("DIMANEGO", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("Bahia Moda", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("Pepita Pérez", "Colombia", "Bucaramanga", "1+", "Retail"),
    ("La Roca Moda Femenina", "Colombia", "Bucaramanga", "1+", "Retail"),
    # TOLUCA (Estado de México)
    ("Fashion Trend Toluca", "Mexico", "Toluca", "1+", "Retail"),
    ("Lefties Toluca", "Mexico", "Toluca", "1+", "Retail"),
    ("SANTORY", "Mexico", "Toluca", "1+", "Retail"),
    ("Fashionista México", "Mexico", "Toluca", "1+", "Retail"),
    ("Gap Toluca", "Mexico", "Toluca", "1+", "Retail"),
    ("Men's Fashion Toluca Centro", "Mexico", "Toluca", "1+", "Retail"),
    ("Bershka Toluca", "Mexico", "Toluca", "1+", "Retail"),
    ("Milano Toluca", "Mexico", "Toluca", "1+", "Retail"),
    ("Salvaje Tentación Juárez I", "Mexico", "Toluca", "1+", "Retail"),
    ("Magaly Moises Boutique", "Mexico", "Toluca", "1+", "Retail"),
    # CARTAGENA (Bolívar)
    ("SOLO MODA", "Colombia", "Cartagena", "1+", "Retail"),
    ("Elizabeth Herrera Boutique Cartagena", "Colombia", "Cartagena", "1+", "Retail"),
    ("Boutique Gabriel", "Colombia", "Cartagena", "1+", "Retail"),
    ("Darte bless boutique Cartagena", "Colombia", "Cartagena", "1+", "Retail"),
    ("El gigante de la moda", "Colombia", "Cartagena", "1+", "Retail"),
    ("REVIEW", "Colombia", "Cartagena", "1+", "Retail"),
    ("Kímbara Cartagena", "Colombia", "Cartagena", "1+", "Retail"),
    ("Boutique Rafaella", "Colombia", "Cartagena", "1+", "Retail"),
    ("SILVERA BOUTIQUE", "Colombia", "Cartagena", "1+", "Retail"),
    # CHOLULA (Puebla)
    ("LA MONARCA - TEXTILES TRADICIONALES ÚNICOS", "Mexico", "Cholula", "1+", "Retail"),
    ("Lupe Báez Vintage", "Mexico", "Cholula", "1+", "Retail"),
    ("La boutique", "Mexico", "Cholula", "1+", "Retail"),
    ("Vertiche Cholula", "Mexico", "Cholula", "1+", "Retail"),
    ("Puerto Varón", "Mexico", "Cholula", "1+", "Retail"),
    ("CASA BOGA Boutique", "Mexico", "Cholula", "1+", "Retail"),
    ("Mine Boutique Cholula", "Mexico", "Cholula", "1+", "Retail"),
    ("SODA OUTFITTERS", "Mexico", "Cholula", "1+", "Retail"),
    ("Espíritu Libre ATELIER", "Mexico", "Cholula", "1+", "Retail"),
    ("Plaza San Diego Cholula", "Mexico", "Cholula", "1+", "Retail"),
    # SALTILLO (Coahuila)
    ("dress4you", "Mexico", "Saltillo", "1+", "Retail"),
    ("Closet Americano Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Vonne Boutique Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Plaza Patio Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Boutique D' Billy Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Promoda Plaza Real Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Localia Concept Store", "Mexico", "Saltillo", "1+", "Retail"),
    ("H&M Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Shasa Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    ("Ropa y Accesorios MB Saltillo", "Mexico", "Saltillo", "1+", "Retail"),
    # ZAPOPAN (Jalisco)
    ("Doris Loo Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("Jazz Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("Love Fashion Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("RM AND DRESS BOUTIQUE", "Mexico", "Zapopan", "1+", "Retail"),
    ("GM Boutique Salón", "Mexico", "Zapopan", "1+", "Retail"),
    ("FASHION LIMON", "Mexico", "Zapopan", "1+", "Retail"),
    ("Brunetta Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("INEZ Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("Level boutique", "Mexico", "Zapopan", "1+", "Retail"),
    ("Rojo Carmín Boutique", "Mexico", "Zapopan", "1+", "Retail"),
    # AGUASCALIENTES
    ("ZARA Aguascalientes", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("VERTICHE Aguascalientes", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("MODA A DOMICILIO", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("Be Fashion Boutique", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("Caprichos Moda Curvy Boutique", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("H&M Aguascalientes", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("K&L Boutique", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("Maria Boutique", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("Bershka Aguascalientes", "Mexico", "Aguascalientes", "1+", "Retail"),
    ("ENMODATE", "Mexico", "Aguascalientes", "1+", "Retail"),
    # MAZATLÁN (Sinaloa)
    ("MX Boutique", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Yadira Rosette", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Angies Fashion Attitude", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Women's Clothing by shirel", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Angies Boutique", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Zona rosa boutique", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Mazatleco Clothing", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Santorino Trendy Boutique", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Ximena's cotton clothing", "Mexico", "Mazatlán", "1+", "Retail"),
    ("Paulo Osuna Shop", "Mexico", "Mazatlán", "1+", "Retail"),
    # VILLAHERMOSA (Tabasco)
    ("DORIS Villahermosa", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Rachel Boutique", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Andrus Boutique Bodas y XV Años", "Mexico", "Villahermosa", "1+", "Retail"),
    ("La boutique de villa", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Dress Avenue", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Rosa y menta showroom Villahermosa", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Romance Boutique", "Mexico", "Villahermosa", "1+", "Retail"),
    ("EA Boutique", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Empire Luxury & Fashion Boutique", "Mexico", "Villahermosa", "1+", "Retail"),
    ("Enamora Boutique", "Mexico", "Villahermosa", "1+", "Retail"),
    # OAXACA (Oaxaca)
    ("ModArte Boutique Oaxaca", "Mexico", "Oaxaca", "1+", "Retail"),
    ("HEFESTOS moda", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Juana La Vintage", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Janekos Moda", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Blur Fashion Boutique", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Dacanni", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Promoda Macroplaza Oaxaca", "Mexico", "Oaxaca", "1+", "Retail"),
    ("VERTICHE Oaxaca", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Hefestos moda Casa Guerrero", "Mexico", "Oaxaca", "1+", "Retail"),
    ("Promoda Plaza Bella Oaxaca", "Mexico", "Oaxaca", "1+", "Retail"),
    # VERACRUZ
    ("Glam Boutique", "Mexico", "Veracruz", "1+", "Retail"),
    ("LECO Boutique", "Mexico", "Veracruz", "1+", "Retail"),
    ("Amour Boutique", "Mexico", "Veracruz", "1+", "Retail"),
    ("NICE GIRL BOUTIQUE", "Mexico", "Veracruz", "1+", "Retail"),
    ("Aloha Moda", "Mexico", "Veracruz", "1+", "Retail"),
    ("Faith & love Boutique", "Mexico", "Veracruz", "1+", "Retail"),
    ("Boutique Mirel", "Mexico", "Veracruz", "1+", "Retail"),
    ("Boutique Celebra Veracruz Centro", "Mexico", "Veracruz", "1+", "Retail"),
    ("Mariana Condado Vestidos de 15 años", "Mexico", "Veracruz", "1+", "Retail"),
    ("El Ropero Boutique", "Mexico", "Veracruz", "1+", "Retail"),
    # EXTRA CITIES - Merida, Querétaro, etc.
    ("Vips Chic", "Mexico", "Mérida", "1+", "Retail"),
    ("Bershka Mérida", "Mexico", "Mérida", "1+", "Retail"),
    ("Shasa Mérida", "Mexico", "Mérida", "1+", "Retail"),
    ("Lefties Mérida", "Mexico", "Mérida", "1+", "Retail"),
    ("OGGI", "Mexico", "Mérida", "1+", "Retail"),
    ("Palasso Boutique", "Mexico", "Mérida", "1+", "Retail"),
    ("Vainilla", "Mexico", "Mérida", "1+", "Retail"),
    ("Coco Blue", "Mexico", "Mérida", "1+", "Retail"),
    ("Mawi", "Mexico", "Mérida", "1+", "Retail"),
    ("Boutique Kukulcán", "Mexico", "Mérida", "1+", "Retail"),
    # SAN LUIS POTOSÍ
    ("Bershka San Luis Potosí", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Shasa San Luis Potosí", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("MODA Santiago", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Boutique É LANE", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Gosh", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Mao", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Dannik", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("Pink", "Mexico", "San Luis Potosí", "1+", "Retail"),
    ("La Boutique San Luis", "Mexico", "San Luis Potosí", "1+", "Retail"),
    # MORELOS - Cuernavaca
    ("Shasa Cuernavaca", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Bershka Cuernavaca", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Vicky", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Boutique Chic Cuernavaca", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Dafne Boutique", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Morena", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("La Casa de la Ropa", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Olivia Boutique", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("Claudia G", "Mexico", "Cuernavaca", "1+", "Retail"),
    ("La Skate", "Mexico", "Cuernavaca", "1+", "Retail"),
    # BOGOTÁ - additional
    ("Bershka Bogotá", "Colombia", "Bogotá", "1+", "Retail"),
    ("Shasa Bogotá", "Colombia", "Bogotá", "1+", "Retail"),
    ("MODA Bogotá", "Colombia", "Bogotá", "1+", "Retail"),
    ("Dafne Boutique Bogotá", "Colombia", "Bogotá", "1+", "Retail"),
    ("Americanino", "Colombia", "Bogotá", "1+", "Retail"),
    ("Roberto Bock", "Colombia", "Bogotá", "1+", "Retail"),
    ("Café Brittney", "Colombia", "Bogotá", "1+", "Retail"),
    ("MLC Store Bogotá", "Colombia", "Bogotá", "1+", "Retail"),
    ("Boutique L Nora", "Colombia", "Bogotá", "1+", "Retail"),
    ("Gina", "Colombia", "Bogotá", "1+", "Retail"),
]

# Read existing companies
existing = set()
with open('/Users/nicolasbermudez/Documents/OptiStockAI/master_leads.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    next(reader)  # skip header
    for row in reader:
        if row:
            existing.add(row[0].strip().lower())

# Add new companies
added = 0
with open('/Users/nicolasbermudez/Documents/OptiStockAI/master_leads.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    for company, country, city, stores, industry in new_companies:
        if company.lower() not in existing:
            writer.writerow([company, '', country, city, stores, industry, '', '', '', 'gplaces_new', 'New', '', '', ''])
            existing.add(company.lower())
            added += 1

print(f"Added {added} new companies")
